name: Release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  release-windows:
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly
          target: x86_64-pc-windows-gnu
      - name: Build
        run: cargo build --release --target x86_64-pc-windows-gnu
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: jackthebox.dll
          path: |
            target/x86_64-pc-windows-gnu/release/jackthebox.dll
