name: Release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  release-windows:
    name: Build & Release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
      - name: Install dotnet toolchain
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.x'
      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
      - name: Build
        run: cargo build --release --verbose
      - name: Upload to releases
        uses: softprops/action-gh-release@v1
        with:
          tag_name: master
          files: |
            target/release/jackthebox.dll
